# Generated by Django 4.1.1 on 2022-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='cxd',
            new_name='date_of_expiration',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_of_acceptance',
            field=models.DateField(blank=True, null=True, verbose_name='contract acceptance date'),
        ),
    ]
