# Generated by Django 4.1.1 on 2022-10-03 16:47

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_cxd_supplier_date_of_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contract_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_of_expiration',
            field=models.DateTimeField(blank=True,  null=True, verbose_name='contract expiration date'),
        ),
    ]
