# Generated by Django 4.1.1 on 2022-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_supplier_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contract_plan',
            field=models.CharField(blank=True, choices=[(None, '--Please choose--'), ('yearly', 'yearly'), ('3years', '3years'), ('5years', '5years')], max_length=30, null=True, verbose_name='contract plan'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_of_expiration',
            field=models.DateField(verbose_name='contract expiration date'),
        ),
    ]
