# Generated by Django 4.1.1 on 2022-10-04 05:49

import django.core.validators
from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_supplier_contract_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contract_code',
            field=models.CharField(default=seller.models.getUniqueCode, max_length=20, verbose_name='contract code'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contract_plan',
            field=models.CharField(choices=[(None, '--Please choose--'), ('yearly', 'yearly'), ('3years', '3years'), ('5years', '5years')], default='yearly', max_length=30, verbose_name='contract plan'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_of_acceptance',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_of_expiration',
            field=models.DateField(help_text='The contract expired; need renewed to use webapp.', validators=[seller.models.validate_future_date], verbose_name='contract expiration date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, help_text='A valid email address.', max_length=100, null=True),
        ),
    ]
