# Generated by Django 4.1.3 on 2023-01-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_supplier_date_of_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='business_type',
            field=models.CharField(choices=[(None, '--Please choose--'), ('Product', 'product'), ('service', 'service')], default='product', max_length=30, verbose_name='business type'),
        ),
    ]
