# Generated by Django 4.1.3 on 2023-01-22 06:08

from django.db import migrations, models
import django.db.models.deletion
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_supplier_business_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='confirmation',
            new_name='states',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contract_code',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contract_plan',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contract_status',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_of_acceptance',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='date_of_expiration',
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(default=seller.models.getUniqueCode, max_length=20, verbose_name='contract code')),
                ('contract_plan', models.CharField(choices=[(None, '--Please choose--'), ('yearly', 'yearly'), ('3years', '3years'), ('5years', '5years')], default='yearly', max_length=30, verbose_name='contract plan')),
                ('date_of_acceptance', models.DateField(auto_now_add=True, null=True)),
                ('date_of_expiration', models.DateField(help_text='contract expiration date', validators=[seller.models.validate_future_date], verbose_name='contract expiration date')),
                ('contract_with', models.CharField(default='autoZoom.inc', max_length=100)),
                ('contract_status', models.CharField(choices=[(None, '--Please choose--'), ('active', 'active'), ('pending', 'pending'), ('suspended', 'suspended')], default='pending', max_length=30)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.supplier')),
            ],
        ),
    ]
