# Generated by Django 4.1.3 on 2023-01-23 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_confirmation_supplier_states_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_location',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
