# Generated by Django 4.1.1 on 2022-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-product_name',)},
        ),
        migrations.AlterField(
            model_name='cost',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
