# Generated by Django 4.1.1 on 2022-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_cost_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='recite_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
