# Generated by Django 4.1.1 on 2022-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_descriptions_application_descriptions_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptions',
            name='measurement',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(blank=True, choices=[(None, '--Please choose--'), ('Free', 'Free'), ('Not Free', 'Not Free'), ('Buy 5+ get free', 'Buy 5+ get free'), ('let you know on checkout', 'let you know on checkout')], max_length=30, null=True),
        ),
    ]
