# Generated by Django 4.1.1 on 2022-10-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('products', '0007_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seller.supplier'),
        ),
        migrations.AlterField(
            model_name='stock_info',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seller.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Supplier_location',
        ),
    ]
