# Generated by Django 4.1.3 on 2022-12-29 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_supplier_date_of_expiration'),
        ('products', '0008_alter_service_supplier_alter_stock_info_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_info',
            name='Supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seller.supplier'),
        ),
    ]
