# Generated by Django 4.1.3 on 2023-01-02 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_stock_info_supplier_product_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='part_number',
            new_name='service_number',
        ),
    ]
