# Generated by Django 4.1.3 on 2023-01-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_rename_confirmation_supplier_states_and_more'),
        ('products', '0010_rename_part_number_service_service_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('part_number', models.CharField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('off_price_parentage', models.SmallIntegerField(blank=True, null=True)),
                ('off_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('shelf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping', models.CharField(blank=True, choices=[(None, '--Please choose--'), ('Free', 'Free'), ('Not Free', 'Not Free'), ('on Stor pickup', 'on Stor pickup'), ('Buy 5+ get free', 'Buy 5+ get free'), ('let you know on checkout', 'let you know on checkout')], max_length=30, null=True)),
                ('tags', models.CharField(choices=[(None, '--Please choose--'), ('sell', 'sell'), ('Hot', 'Hot'), ('Fast moving', 'Fast moving')], max_length=30)),
                ('label', models.CharField(choices=[(None, '--Please choose--'), ('Bast seller', 'Bast seller'), ('AutoZoom Choice', 'AutoZoom Choice'), ('New', 'New')], max_length=30)),
                ('return_police', models.CharField(choices=[(None, '--Please choose--'), ('No Return', 'No Return'), ('same day', 'same day'), ('seven days', 'seven days'), ('Fifteen(15) days', 'Fifteen(15) days'), ('Thirty(30) days', 'Thirty(30) days')], max_length=30)),
                ('product_states', models.CharField(choices=[(None, '--Please choose--'), ('New Brand', 'New Brand'), ('Used', 'Used'), ('Refurnished', 'Refurnished'), ('Open Box', 'Open Box')], max_length=30)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(default=1)),
                ('location_lick', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.CharField(blank=True, default='www.autoZoom.com', max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('wereda_kebela', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seller.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='stock_info',
            name='product_location',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='product_states',
        ),
        migrations.AddField(
            model_name='brand',
            name='manufactured_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='instraction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='descriptions',
            name='warning',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture5',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='picture',
            name='picture6',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='application',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='industry',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='measurement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_location',
        ),
        migrations.DeleteModel(
            name='Stock_info',
        ),
        migrations.AddField(
            model_name='product_stock',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AddField(
            model_name='product_stock',
            name='cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cost'),
        ),
        migrations.AddField(
            model_name='product_stock',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.picture'),
        ),
        migrations.AddField(
            model_name='product_stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product_information'),
        ),
        migrations.AddField(
            model_name='product_stock',
            name='store',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.store'),
        ),
        migrations.AddField(
            model_name='product_information',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.descriptions'),
        ),
    ]
