# Generated by Django 4.1.3 on 2023-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_cost_distribution_rat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_product',
            name='cost_add_present',
            field=models.SmallIntegerField(default=0),
        ),
    ]
