# Generated by Django 4.1.3 on 2023-01-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_supplier_location_slug'),
        ('products', '0017_alter_product_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_stock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.supplier'),
        ),
        migrations.AlterField(
            model_name='product_stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.purchased_product'),
        ),
        migrations.AlterField(
            model_name='product_stock',
            name='store',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.store'),
        ),
    ]
