# Generated by Django 4.1.3 on 2023-01-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_stock_supplier_alter_product_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.purchased_product'),
        ),
    ]
